language: go

go:
- 1.20

env:
- GO111MODULE=on

before_script:
- go install golang.org/x/tools/cmd/cover@latest
- go install github.com/mattn/goveralls@latest

script:
- go test -covermode=count -coverprofile=profile.cov ./...
- goveralls -coverprofile=profile.cov -service=travis-ci
